# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d39c196b2e0a94f6a22613fa99cb012838907b4fc8d1a977b0911b78d897ebfde80c48ac70ddc1214e680dca066b152b3304ad5b43c753860ba4fb480148398

test:
  secret_key_base: b9a80c6a94733f4be00124a0037029d14168dcfc2f5819b0ef841b5c7372954b82309d5111c8eea3ac625cb146d28a55414eb86343da11bb349d6e1b2606bf10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
